export default {
  /* These will be applied as inline styles */
  staticProps: [
    'flexDirection',
    'flexFlow',
    'flexWrap',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    'alignContent',
    'alignItems',
    'alignSelf',
    'placeContent',
    'placeItems',
  ],

  /* These will be applied as dynamically embedded as inline css */
  dynamicProps: ['flex', 'flexBasis', 'flexGrow', 'flexShrink', 'order'],

  /**
   * Flex property values
   */
  flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
  flexWrap: ['nowrap', 'wrap', 'wrap-reverse'],
  justifyContent: [
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'left',
    'right',
    'normal',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'safe center',
    'unsafe center',
  ],
  justifyItems: [
    'auto',
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'self-start',
    'self-end',
    'left',
    'right',
    'baseline',
    'first baseline',
    'last baseline',
    'safe center',
    'unsafe center',
    'legacy right',
    'legacy left',
    'legacy center',
  ],
  justifySelf: [
    'auto',
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'self-start',
    'self-end',
    'left',
    'right',
    'baseline',
    'first baseline',
    'last baseline',
    'safe center',
    'unsafe center',
  ],
  alignContent: [
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'normal',
    'baseline',
    'first baseline',
    'last baseline',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'safe center',
    'unsafe center',
  ],
  alignItems: [
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'self-start',
    'self-end',
    'baseline',
    'first baseline',
    'last baseline',
    'safe center',
    'unsafe center',
  ],
  alignSelf: [
    'auto',
    'normal',
    'center',
    'start',
    'end',
    'self-start',
    'self-end',
    'flex-start',
    'flex-end',
    'baseline',
    'first baseline',
    'last baseline',
    'stretch',
    'safe center',
    'unsafe center',
  ],
  globalPropValues: ['inherit', 'initial', 'unset'],
};
